name: CI
on: [push,  pull_request]
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
      - users: actions/checkout@v2
      - name: Test using Node.js
      - run: npm install
      - run: npx jest
